# Generated by Django 4.2.12 on 2024-10-01 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('symbol', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_capital', models.FloatField()),
                ('risk_aversion', models.FloatField()),
                ('weight', models.FloatField()),
                ('new_position', models.FloatField()),
                ('new_weight', models.FloatField()),
                ('date_allocated', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortfolioAllocation_app.asset')),
            ],
            options={
                'verbose_name': 'Portfolio Allocation',
                'verbose_name_plural': 'Portfolio Allocations',
                'ordering': ['-date_allocated'],
            },
        ),
    ]
